{
 "title": "Painel pontuação ansiedade",
 "time": { "from": "2023-10-19T09:36:33.000Z", "to": "2023-10-19T11:36:33.000Z" },
 "panels": [
  {
   "title": "Número de respostas",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(*) FROM respostas" }
   ]
  },
  {
   "title": "Gênero Masculino",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM respostas\nINNER JOIN public.participantes p on p.id = respostas.participante_id\nWHERE p.genero = 'Masculino'"
    }
   ]
  },
  {
   "title": "Participantes por faixa etária",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    count(1),\n    (SELECT count(*) FROM participantes WHERE idade BETWEEN 0 AND 18) as \"Até 18 anos\",\n    (SELECT count(*) FROM participantes WHERE idade BETWEEN 19 AND 34) as \"19 até 34 anos\",\n    (SELECT count(*) FROM participantes WHERE idade BETWEEN 35 AND 50) as \"35 até 50 anos\",\n    (SELECT count(*) FROM participantes WHERE idade BETWEEN 51 AND 999) as \"Acima de 50 anos\"\nFROM participantes;"
    }
   ]
  },
  {
   "title": "Gênero Feminino",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM respostas\nINNER JOIN public.participantes p on p.id = respostas.participante_id\nWHERE p.genero = 'Feminino'"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "options": { "content": " \n " } },
  {
   "title": "Pontuação Depressão",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    count(1),\n    (SELECT count(*) FROM respostas WHERE pontuacao_total_depressao BETWEEN 0 AND 4) as \"0 - Sem sintomas\",\n    (SELECT count(*) FROM respostas WHERE pontuacao_total_depressao BETWEEN 5 AND 6) as \"1 - Sintomas leves\",\n    (SELECT count(*) FROM respostas WHERE pontuacao_total_depressao BETWEEN 7 AND 10) as \"2 - Sintomas moderados\",\n    (SELECT count(*) FROM respostas WHERE pontuacao_total_depressao BETWEEN 11 AND 13) as \"3 - Sintomas graves\",\n    (SELECT count(*) FROM respostas WHERE pontuacao_total_depressao BETWEEN 14 AND 999) as \"4 - Sintomas muito graves\"\nFROM respostas;"
    }
   ]
  },
  {
   "title": "Pontuação Ansiedade",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    count(1),\n    (SELECT count(*) FROM respostas WHERE pontuacao_total_ansiedade BETWEEN 0 AND 3) as \"0 - Sem sintomas\",\n    (SELECT count(*) FROM respostas WHERE pontuacao_total_ansiedade BETWEEN 4 AND 5) as \"1 - Sintomas leves\",\n    (SELECT count(*) FROM respostas WHERE pontuacao_total_ansiedade BETWEEN 6 AND 7) as \"2 - Sintomas moderados\",\n    (SELECT count(*) FROM respostas WHERE pontuacao_total_ansiedade BETWEEN 8 AND 9) as \"3 - Sintomas graves\",\n    (SELECT count(*) FROM respostas WHERE pontuacao_total_ansiedade BETWEEN 10 AND 999) as \"4 - Sintomas muito graves\"\nFROM respostas;"
    }
   ]
  },
  {
   "title": "Pontuação Estresse",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    count(1),\n    (SELECT count(*) FROM respostas WHERE pontuacao_total_estresse BETWEEN 0 AND 7) as \"0 - Sem sintomas\",\n    (SELECT count(*) FROM respostas WHERE pontuacao_total_estresse BETWEEN 8 AND 9) as \"1 - Sintomas leves\",\n    (SELECT count(*) FROM respostas WHERE pontuacao_total_estresse BETWEEN 10 AND 12) as \"2 - Sintomas moderados\",\n    (SELECT count(*) FROM respostas WHERE pontuacao_total_estresse BETWEEN 13 AND 16) as \"3 - Sintomas graves\",\n    (SELECT count(*) FROM respostas WHERE pontuacao_total_estresse BETWEEN 17 AND 999) as \"4 - Sintomas muito graves\"\nFROM respostas;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: space-between; height: 50px; align-items: center\">\n<span style=\"color: rgb(50, 116, 217)\">0 - Sem sintomas</span>\n<span>|</span>\n<span style=\"color: rgb(86, 166, 75)\">1 - Sintomas leves</span>\n<span>|</span>\n<span style=\"color: rgb(242, 204, 12)\">2 - Sintomas moderados</span>\n<span>|</span>\n<span style=\"color: rgb(255, 120, 10)\">3 - Sintomas graves</span>\n<span>|</span>\n<span style=\"color: rgb(224, 47, 68)\">4 - Sintomas muito graves</span>\n\n</div>"
   }
  }
 ]
}